name: the_puzzle_cell
description: The Puzzle Cell

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dart_vlc: ^0.1.8
  flame: ^1.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.8.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/movers/
    - assets/images/movers/movers/
    - assets/images/backgrounds/
    - assets/images/movers/mirrors/
    - assets/images/rotators/
    - assets/images/push/
    - assets/images/destroyers/
    - assets/images/recreators/
    - assets/images/recreators/supgens/
    - assets/images/recreators/generators/
    - assets/images/recreators/replicators/
    - assets/images/recreators/tunnels/
    - assets/images/recreators/tunnels/warpers/
    - assets/images/curves/
    - assets/images/puzzle/
    - assets/images/interface/
    - assets/audio/
    - assets/puzzles/
    - assets/puzzles/easy/
    - assets/puzzles/medium/
    - assets/puzzles/hard/

# MSIX build shit

msix_config:
  display_name: The Puzzle Cell
  publisher_display_name: A Monitor#1595
  identity_name: Me.ParauIonut.ThePuzzleCell
  msix_version: 1.0.0.0
  logo_path: D:\Workplace\Dart\Flutter\the_puzzle_cell\assets\images\logo.png
  capabilities: "internetClient"
