on: push

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: thepuzzlecell-windows
          path: build/windows/runner/Release
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: sudo apt install vlc
      - run: sudo apt install libvlc-dev
      - run: sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - uses: actions/upload-artifact@v3
        with:
          name: thepuzzlecell-linux
          path: build/linux/x64/release/bundle
  # build_macos:
  #   runs-on: macOS-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #     - run: brew install cmake
  #     - run: gem install cocoapods
  #     - run: flutter pub get
  #     - run: flutter config --enable-macos-desktop
  #     - run: brew install xcode
  #     - run: flutter build macos -v
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: thepuzzlecell-macos
  #         path: build/macos/Build/Products/Release
